AWSTemplateFormatVersion: '2010-09-09'
Description: 'Medical Imaging Workshop - Minimal Infrastructure (Essential Resources Only)'

Parameters:
  WorkshopName:
    Type: String
    Default: 'medical-imaging-workshop'
    Description: 'Name prefix for all workshop resources'
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: 'Must contain only lowercase letters, numbers, and hyphens'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Workshop Configuration'
        Parameters:
          - WorkshopName

Resources:
  # S3 Bucket for workshop data
  WorkshopDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${WorkshopName}-data-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
          - Id: DeleteIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'Medical Imaging Data Storage'

  # S3 Bucket for model artifacts
  WorkshopModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${WorkshopName}-models-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldObjects
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'Model Artifacts Storage'

  # ECR Repository for custom training containers
  ECRTrainingRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${WorkshopName}/training'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'Custom Training Containers'

  # ECR Repository for preprocessing containers
  ECRPreprocessingRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${WorkshopName}/preprocessing'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 3 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'Preprocessing Containers'

  # IAM Role for SageMaker Execution
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${WorkshopName}-SageMakerRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: WorkshopS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${WorkshopDataBucket.Arn}'
                  - !Sub '${WorkshopDataBucket.Arn}/*'
                  - !Sub '${WorkshopModelBucket.Arn}'
                  - !Sub '${WorkshopModelBucket.Arn}/*'
        - PolicyName: WorkshopECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:DescribeRepositories
                  - ecr:DescribeImages
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource:
                  - !GetAtt ECRTrainingRepository.Arn
                  - !GetAtt ECRPreprocessingRepository.Arn
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName

  # IAM Role for EC2 Instances
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${WorkshopName}-EC2Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WorkshopS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${WorkshopDataBucket.Arn}'
                  - !Sub '${WorkshopDataBucket.Arn}/*'
                  - !Sub '${WorkshopModelBucket.Arn}'
                  - !Sub '${WorkshopModelBucket.Arn}/*'
        - PolicyName: WorkshopECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
        - PolicyName: WorkshopSageMakerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:CreateTrainingJob
                  - sagemaker:DescribeTrainingJob
                  - sagemaker:CreateProcessingJob
                  - sagemaker:DescribeProcessingJob
                  - sagemaker:CreateModel
                  - sagemaker:DescribeModel
                  - iam:PassRole
                Resource: '*'
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName

  # Instance Profile for EC2
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${WorkshopName}-EC2Profile'
      Roles:
        - !Ref EC2InstanceRole

  # Security Group for EC2 Instances
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${WorkshopName}-EC2-SG'
      GroupDescription: 'Security group for workshop EC2 instances'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: 'SSH access'
        - IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: 0.0.0.0/0
          Description: 'Jupyter notebook'
      Tags:
        - Key: Name
          Value: !Sub '${WorkshopName}-EC2-SG'
        - Key: Workshop
          Value: !Ref WorkshopName

Outputs:
  WorkshopDataBucket:
    Description: 'S3 bucket for workshop data'
    Value: !Ref WorkshopDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucket'

  WorkshopModelBucket:
    Description: 'S3 bucket for model artifacts'
    Value: !Ref WorkshopModelBucket
    Export:
      Name: !Sub '${AWS::StackName}-ModelBucket'

  SageMakerExecutionRoleArn:
    Description: 'ARN of the SageMaker execution role'
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SageMakerRole'

  EC2InstanceRoleArn:
    Description: 'ARN of the EC2 instance role'
    Value: !GetAtt EC2InstanceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EC2Role'

  EC2InstanceProfileArn:
    Description: 'ARN of the EC2 instance profile'
    Value: !GetAtt EC2InstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EC2Profile'

  EC2SecurityGroupId:
    Description: 'Security group ID for EC2 instances'
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-EC2SecurityGroup'

  ECRTrainingRepositoryURI:
    Description: 'URI of the ECR training repository'
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRTrainingRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-ECRTrainingRepo'

  ECRPreprocessingRepositoryURI:
    Description: 'URI of the ECR preprocessing repository'
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRPreprocessingRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-ECRPreprocessingRepo'

  QuickStartInstructions:
    Description: 'Quick start instructions for workshop participants'
    Value: !Sub |
      Workshop Resources Created:
      
      1. Data Bucket: s3://${WorkshopDataBucket}
      2. Model Bucket: s3://${WorkshopModelBucket}
      3. SageMaker Role: ${SageMakerExecutionRole.Arn}
      4. EC2 Role: ${EC2InstanceRole.Arn}
      5. ECR Training: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRTrainingRepository}
      6. ECR Preprocessing: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRPreprocessingRepository}
      
      Next Steps:
      - Launch EC2 instance using EC2 instance profile
      - Use SageMaker role for training jobs
      - Upload data to data bucket
      - Push containers to ECR repositories
