AWSTemplateFormatVersion: '2010-09-09'
Description: 'Medical Imaging Workshop Infrastructure - Sets up SageMaker, EC2, S3, and IAM resources'

Parameters:
  WorkshopName:
    Type: String
    Default: 'medical-imaging-workshop'
    Description: 'Name prefix for all workshop resources'
    
  ParticipantCount:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 50
    Description: 'Expected number of workshop participants'
    
  EnableEC2Training:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: 'Whether to create EC2 instances for training notebooks'
    
  EC2InstanceType:
    Type: String
    Default: 'g4dn.xlarge'
    AllowedValues: 
      - 'g4dn.xlarge'
      - 'g4dn.2xlarge'
    Description: 'EC2 instance type for GPU training'
    
  SageMakerNotebookInstanceType:
    Type: String
    Default: 'ml.t3.medium'
    AllowedValues:
      - 'ml.t3.medium'
      - 'ml.t3.large'
      - 'ml.m5.large'
      - 'ml.g4dn.xlarge'
    Description: 'SageMaker notebook instance type'
    
  EnableSageMakerStudio:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: 'Whether to create SageMaker Studio Domain (use sagemaker-studio-setup.yaml for Studio-only deployment)'

Conditions:
  CreateEC2Resources: !Equals [!Ref EnableEC2Training, 'true']
  CreateStudioDomain: !Equals [!Ref EnableSageMakerStudio, 'true']

Resources:
  # S3 Bucket for workshop data and artifacts
  WorkshopDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${WorkshopName}-data-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'Medical Imaging Data Storage'

  # S3 Bucket for model artifacts
  WorkshopModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${WorkshopName}-models-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'Model Artifacts Storage'

  # ECR Repository for custom containers
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${WorkshopName}/medical-imaging-training'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'Custom Training Containers'

  # ECR Repository for preprocessing containers
  ECRPreprocessingRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${WorkshopName}/medical-imaging-preprocessing'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName

  # IAM Role for SageMaker Execution
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${WorkshopName}-SageMakerExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WorkshopComprehensivePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3FullAccess
                Effect: Allow
                Action:
                  - s3:*
                Resource: '*'
              - Sid: SageMakerTraining
                Effect: Allow
                Action:
                  - sagemaker:CreateTrainingJob
                  - sagemaker:DescribeTrainingJob
                  - sagemaker:StopTrainingJob
                  - sagemaker:ListTrainingJobs
                  - sagemaker:ListTrainingJobsForHyperParameterTuningJob
                  - sagemaker:AddTags
                  - sagemaker:ListTags
                Resource: '*'
              - Sid: SageMakerHyperParameterTuning
                Effect: Allow
                Action:
                  - sagemaker:CreateHyperParameterTuningJob
                  - sagemaker:DescribeHyperParameterTuningJob
                  - sagemaker:StopHyperParameterTuningJob
                  - sagemaker:ListHyperParameterTuningJobs
                  - sagemaker:UpdateHyperParameterTuningJob
                Resource: '*'
              - Sid: SageMakerModelDeployment
                Effect: Allow
                Action:
                  - sagemaker:CreateModel
                  - sagemaker:DescribeModel
                  - sagemaker:DeleteModel
                  - sagemaker:ListModels
                  - sagemaker:CreateEndpointConfig
                  - sagemaker:DescribeEndpointConfig
                  - sagemaker:DeleteEndpointConfig
                  - sagemaker:ListEndpointConfigs
                  - sagemaker:CreateEndpoint
                  - sagemaker:DescribeEndpoint
                  - sagemaker:DeleteEndpoint
                  - sagemaker:UpdateEndpoint
                  - sagemaker:ListEndpoints
                  - sagemaker:InvokeEndpoint
                Resource: '*'
              - Sid: SageMakerProcessing
                Effect: Allow
                Action:
                  - sagemaker:CreateProcessingJob
                  - sagemaker:DescribeProcessingJob
                  - sagemaker:StopProcessingJob
                  - sagemaker:ListProcessingJobs
                Resource: '*'
              - Sid: SageMakerExperiments
                Effect: Allow
                Action:
                  - sagemaker:CreateExperiment
                  - sagemaker:DescribeExperiment
                  - sagemaker:DeleteExperiment
                  - sagemaker:CreateTrial
                  - sagemaker:DescribeTrial
                  - sagemaker:DeleteTrial
                  - sagemaker:CreateTrialComponent
                  - sagemaker:DescribeTrialComponent
                  - sagemaker:UpdateTrialComponent
                  - sagemaker:DeleteTrialComponent
                  - sagemaker:AssociateTrialComponent
                  - sagemaker:DisassociateTrialComponent
                Resource: '*'
              - Sid: ECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:DescribeRepositories
                  - ecr:DescribeImages
                  - ecr:CreateRepository
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - ecr:BatchDeleteImage
                Resource: '*'
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents
                Resource: '*'
              - Sid: CloudWatchMetrics
                Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                Resource: '*'
              - Sid: IAMPassRole
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
                Condition:
                  StringEquals:
                    iam:PassedToService: sagemaker.amazonaws.com
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName

  # IAM Role for EC2 instances
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Condition: CreateEC2Resources
    Properties:
      RoleName: !Sub '${WorkshopName}-EC2InstanceRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: WorkshopS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${WorkshopDataBucket.Arn}/*'
                  - !Sub '${WorkshopModelBucket.Arn}/*'
                  - !GetAtt WorkshopDataBucket.Arn
                  - !GetAtt WorkshopModelBucket.Arn
        - PolicyName: WorkshopECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:DescribeRepositories
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: '*'
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName

  # Instance Profile for EC2
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Condition: CreateEC2Resources
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  # Security Group for EC2 instances
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateEC2Resources
    Properties:
      GroupName: !Sub '${WorkshopName}-EC2-SecurityGroup'
      GroupDescription: 'Security group for medical imaging workshop EC2 instances'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: 'SSH access'
        - IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: 0.0.0.0/0
          Description: 'Jupyter notebook access'
        - IpProtocol: tcp
          FromPort: 6006
          ToPort: 6006
          CidrIp: 0.0.0.0/0
          Description: 'TensorBoard access'
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName

  # Launch Template for EC2 instances
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Condition: CreateEC2Resources
    DependsOn: EC2SecurityGroup
    Properties:
      LaunchTemplateName: !Sub '${WorkshopName}-EC2-LaunchTemplate'
      LaunchTemplateData:
        ImageId: ami-0c02fb55956c7d316  # Deep Learning AMI (Ubuntu 20.04) - update for your region
        InstanceType: !Ref EC2InstanceType
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        SecurityGroupIds:
          - !GetAtt EC2SecurityGroup.GroupId
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 100
              VolumeType: gp3
              DeleteOnTermination: true
              Encrypted: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            
            # Install additional packages
            /opt/conda/bin/pip install monai==1.4.0
            /opt/conda/bin/pip install nibabel==5.1.0
            /opt/conda/bin/pip install simpleitk==2.3.1
            /opt/conda/bin/pip install grad-cam pytorch-grad-cam
            /opt/conda/bin/pip install sagemaker boto3
            
            # Configure AWS CLI with region
            sudo -u ec2-user aws configure set region ${AWS::Region}
            
            # Create startup script for Jupyter
            cat > /home/ec2-user/start-jupyter.sh << 'EOF'
            #!/bin/bash
            cd /home/ec2-user
            /opt/conda/bin/jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
            EOF
            chmod +x /home/ec2-user/start-jupyter.sh
            chown ec2-user:ec2-user /home/ec2-user/start-jupyter.sh
            
            # Create README
            cat > /home/ec2-user/README.txt << 'EOF'
            Medical Imaging Workshop - EC2 Instance
            
            To get started:
            1. Clone your workshop repository: git clone YOUR-REPO-URL
            2. Start Jupyter: ./start-jupyter.sh
            3. Access Jupyter at: http://YOUR-PUBLIC-IP:8888
            
            Pre-installed packages:
            - PyTorch with CUDA
            - MONAI, nibabel, SimpleITK
            - SageMaker SDK
            EOF
            chown ec2-user:ec2-user /home/ec2-user/README.txt
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${WorkshopName}-Training-Instance'
              - Key: Workshop
                Value: !Ref WorkshopName
              - Key: Purpose
                Value: 'GPU Training'

  # SageMaker Notebook Instance
  SageMakerNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Sub '${WorkshopName}-notebook-instance'
      InstanceType: !Ref SageMakerNotebookInstanceType
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      VolumeSizeInGB: 20
      Tags:
        - Key: Workshop
          Value: !Ref WorkshopName
        - Key: Purpose
          Value: 'SageMaker Development'

  # CloudWatch Dashboard for monitoring
  WorkshopDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${WorkshopName}-Dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/SageMaker", "TrainingJobsInProgress" ],
                  [ ".", "TrainingJobsCompleted" ],
                  [ ".", "TrainingJobsFailed" ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "SageMaker Training Jobs"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/S3", "BucketSizeBytes", "BucketName", "${WorkshopDataBucket}", "StorageType", "StandardStorage" ]
                ],
                "period": 86400,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "S3 Storage Usage"
              }
            }
          ]
        }

Outputs:
  WorkshopDataBucket:
    Description: 'S3 bucket for workshop data'
    Value: !Ref WorkshopDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucket'

  WorkshopModelBucket:
    Description: 'S3 bucket for model artifacts'
    Value: !Ref WorkshopModelBucket
    Export:
      Name: !Sub '${AWS::StackName}-ModelBucket'

  SageMakerExecutionRoleArn:
    Description: 'ARN of the SageMaker execution role'
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SageMakerRole'

  ECRRepositoryURI:
    Description: 'URI of the ECR repository for training containers'
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepository'

  ECRPreprocessingRepositoryURI:
    Description: 'URI of the ECR repository for preprocessing containers'
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRPreprocessingRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-ECRPreprocessingRepository'

  SageMakerNotebookInstanceName:
    Description: 'Name of the SageMaker notebook instance'
    Value: !Ref SageMakerNotebookInstance
    Export:
      Name: !Sub '${AWS::StackName}-NotebookInstance'

  EC2LaunchTemplateId:
    Condition: CreateEC2Resources
    Description: 'ID of the EC2 launch template'
    Value: !Ref EC2LaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-EC2LaunchTemplate'

  WorkshopDashboardURL:
    Description: 'URL to the CloudWatch dashboard'
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${WorkshopName}-Dashboard'

  QuickStartInstructions:
    Description: 'Quick start instructions for workshop participants'
    Value: !Sub |
      1. SageMaker Notebook: https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/${SageMakerNotebookInstance}
      2. Data Bucket: s3://${WorkshopDataBucket}
      3. Model Bucket: s3://${WorkshopModelBucket}
      4. ECR Repository: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}